apiVersion: v1
kind: Template
metadata:
  name: ${APPLICATION_NAME}-persistent
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-postgresql
  spec:
    ports:

    - name: ${APPLICATION_NAME}-postgresql
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      name: ${APPLICATION_NAME}-postgresql
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-postgresql
  spec:
    replicas: 1
    selector:
      name: ${APPLICATION_NAME}-postgresql
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
          name: ${APPLICATION_NAME}-postgresql
      spec:
        containers:
        - env:
          - name: POSTGRESQL_USER
            value: ${POSTGRESQL_USER}
          - name: POSTGRESQL_PASSWORD
            value: ${POSTGRESQL_PASSWORD}
          - name: POSTGRESQL_DATABASE
            value: ${POSTGRESQL_DATABASE}
          image: rhscl/postgresql-95-rhel7
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 5432
            timeoutSeconds: 1
          name: ${APPLICATION_NAME}-postgresql
          ports:
          - containerPort: 5432
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /usr/libexec/check-container
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            exec:
              command:
              - /usr/libexec/check-container
              - --live
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: ${POSTGRESQL_LIMIT_CPU}
              memory: ${POSTGRESQL_LIMIT_MEM}
            requests:
              cpu: ${POSTGRESQL_REQUEST_CPU}
              memory: ${POSTGRESQL_REQUEST_MEM}
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/lib/pgsql/data
            name: ${APPLICATION_NAME}-postgresql-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: ${APPLICATION_NAME}-postgresql-data
          persistentVolumeClaim:
            claimName: ${APPLICATION_NAME}-postgresql
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}-postgresql
        from:
          kind: ImageStreamTag
          name: postgresql:${POSTGRESQL_VERSION}
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}-postgresql
  spec:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: ${POSTGRESQL_VOLUME_CAPACITY}
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: ${APPLICATION_VOLUME_CAPACITY}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    tags:
    - from:
        kind: DockerImage
        name: docker.io/openshiftdemos/${APPLICATION_NAME}:${SONARQUBE_VERSION}
      name: ${SONARQUBE_VERSION}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/dependencies: '[{"name":"${APPLICATION_NAME}-postgresql","namespace":"","kind":"Service"}]'
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - name: 9000-tcp
      port: 9000
      protocol: TCP
      targetPort: 9000
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    port:
      targetPort: 9000-tcp
    to:
      kind: Service
      name: ${APPLICATION_NAME}
      weight: 100
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
          deploymentconfig: ${APPLICATION_NAME}
      spec:
        containers:
        - env:
          - name: SONARQUBE_JDBC_PASSWORD
            value: ${POSTGRESQL_PASSWORD}
          - name: SONARQUBE_JDBC_URL
            value: jdbc:postgresql://${APPLICATION_NAME}-postgresql/${POSTGRESQL_DATABASE}
          - name: SONARQUBE_JDBC_USERNAME
            value: ${POSTGRESQL_USER}
          image: docker.io/openshiftdemos/${APPLICATION_NAME}
          imagePullPolicy: IfNotPresent
          name: ${APPLICATION_NAME}
          resources:
            limits:
              cpu: ${SONARQUBE_LIMIT_CPU}
              memory: ${SONARQUBE_LIMIT_MEM}
            requests:
              cpu: ${SONARQUBE_REQUEST_CPU}
              memory: ${SONARQUBE_REQUEST_MEM}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
            - mountPath: /opt/sonarqube/extensions/plugins
              name: ${APPLICATION_NAME}-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: 
          runAsUser: 1000100001
        terminationGracePeriodSeconds: 30
        volumes:
        - name: ${APPLICATION_NAME}-data
          persistentVolumeClaim:
            claimName: ${APPLICATION_NAME}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:${SONARQUBE_VERSION}
      type: ImageChange
parameters:
- description: The exposed route/host name
  name: HOST_NAME
  required: false
- description: The name for the application
  name: APPLICATION_NAME
  required: true
  value: sonarqube
- description: SonarQube version
  displayName: SonarQube version
  name: SONARQUBE_VERSION
  required: true
  value: "6.0"
- description: PostgreSQL Volume Capacity
  name: POSTGRESQL_VOLUME_CAPACITY
  required: true
  value: 2Gi
- description: Application Volume Capacity
  name: APPLICATION_VOLUME_CAPACITY
  required: true
  value: 2Gi
- description: Postgresql Database
  displayName: Postgresql Database
  name: POSTGRESQL_DATABASE
  required: true
  value: sonar
- description: Postgresql Version
  displayName: Postgresql Version
  name: POSTGRESQL_VERSION
  required: true
  value: "9.6"
- description: Postgresql User
  displayName: Postgresql User
  name: POSTGRESQL_USER
  required: true
  value: sonar
- description: Postgresql Password
  displayName: Postgresql Password
  name: POSTGRESQL_PASSWORD
  from: '[a-zA-Z0-9]{8}'
  value: sonar
- name: SONARQUBE_LIMIT_CPU
  displayName: Sonar Qube CPU Resource Limit
  description: Sonar Qube container resource limit for CPU
  value: "600m"
- name:	SONARQUBE_REQUEST_CPU
  displayName: Sonar Qube CPU Resource Request Limit         	              
  description: Sonar Qube container resource request limit for CPU                   
  value: "50m"
- name:	SONARQUBE_LIMIT_MEM
  displayName: Sonar Qube Memory Resource Limit         	              
  description: Sonar Qube container resource limit for memory                   
  value: "1Gi"
- name:	SONARQUBE_REQUEST_MEM
  displayName: Sonar Qube Memory Resource Request Limit         	              
  description: Sonar Qube container resource request limit for memory                   
  value: "50Mi"
- name: POSTGRESQL_LIMIT_CPU
  displayName: PostgreSQL CPU Resource Limit
  description: PostgreSQL container resource limit for CPU
  value: "600m"
- name: POSTGRESQL_REQUEST_CPU
  displayName: PostgreSQL CPU Resource Request Limit
  description: PostgreSQL container resource request limit for CPU
  value: "50m"
- name: POSTGRESQL_LIMIT_MEM
  displayName: PostgreSQL Memory Resource Limit
  description: PostgreSQL container resource limit for memory
  value: "1Gi"
- name: POSTGRESQL_REQUEST_MEM
  displayName: PostgreSQL Memory Resource Request Limit
  description: PostgreSQL container resource request limit for memory
  value: "50Mi"
